name = the_shire
title = The Shire
description = Adds simple hobbit-themed doors, windows, paths, and covered grass blocks.
depends = default, stairs
author = Copyright (c) 2015-2026TumeniNoeds
license = Code: MIT / LGPL-2.1, Media: CC-BY-SA 4.0

